package Common;

public enum Code {
	AUTHENTICATE_USERNAME,
	AUTHENTICATE_EMAIL,
	AUTHENTICATE_FAIL,
	AUTHENTICATE_SUCCESS,
	AUTHENTICATE_SUCCESS_ADMIN,
	REGISTRATION,
	REGISTRATION_SUCCESS,
	REGISTRATION_FAIL,
	GET_USER_ID_BY_EMAIL,
	GET_USER_ID_BY_USERNAME,
	SUCCESS,
	GET_EXCURSIONS,
	BOOKED,
	BOOKED_WAIT_LIST,
	BOOK_REQUEST,
	BOOK_REMOVE_PASSENGERS,
	BOOKED_ALREADY,
	BOOK_FULL,
	GET_USER_EXCURSIONS,
	EDIT_REQUEST,
	EDIT_SUCCESS,
	CANCEL_REQUEST,
	FAIL,
	ADMIN_BOOKINGS_REQUEST
}
